config/routes.rb
Cheeks::Application.routes.draw do
  resources :locations

  root "pages#home"
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"
  get "/contact", to: "pages#contact", as: "contact"
  post "/emailconfirmation", to: "pages#email", as: "email_confirmation"

  get "wedding", to: "pages#wedding", as: "wedding"
  get "travel", to: "pages#travel", as: "travel"
  get "about", to: "pages#about", as: "about"
  get "activities", to: "pages#activities", as: "activities"

  get "posts", to: "pages#posts", as: "posts"
  get "posts/:id", to: "pages#show_post", as: "post"
  devise_for :users

  namespace :admin do
    root "base#index"
    resources :users
    get "posts/drafts", to: "posts#drafts", as: "posts_drafts"
    get "posts/dashboard", to: "posts#dashboard", as: "posts_dashboard"
    resources :posts
  end

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_filter :require_admin!
  
  def index
    @last_signups = User.last_signups(10)
    @last_signins = User.last_signins(10)
    @count = User.users_count 
    @post_count = Post.count
  end
end

app/views/admin/base/index.html.erb
<% title("Admin") %>
<h1>Admin <small>Home</small></h1>
<div class="row">
  <div class="col-sm-4">
    <h3>Menu</h3>
    <h4><%= link_to "Users", admin_users_path %> <small>- <%= "#{pluralize(@count, 'user')}" %></small></h4>
    <h4><%= link_to "Posts", admin_posts_dashboard_path %> <small>- <%= "#{pluralize(@post_count, 'post')}" %></small></h4>
    <hr/>
  </div>
  
  <div class="col-sm-4">
    <h3>Last Sign Ups</h3>
    <ul class="list-unstyled">
      <% @last_signups.each do |user| %>
      <li class="list-padded-bottom">
        <%= link_to user.email, edit_admin_user_path(user) %><br/>
        <small><%= time_ago_in_words(user.created_at)%> ago</small>
      </li>
      <% end %>
    </ul>
  </div>
  
  <div class="col-sm-4">
    <h3>Last Sign Ins</h3>
    <ul class="list-unstyled">
      <% @last_signins.each do |user| %>
      <li class="list-padded-bottom">
        <%= link_to user.email, edit_admin_user_path(user) %><br/>
        <small>
          <% unless user.last_sign_in_at.nil? %>
          <%= time_ago_in_words(user.last_sign_in_at)%> ago
          <% else %>
          never
          <% end %>
        </small>
      </li>
      <% end %>
    </ul>
  </div>
  
</div>