config/routes.rb
Cheeks::Application.routes.draw do
  resources :locations

  root "pages#home"
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"
  get "/contact", to: "pages#contact", as: "contact"
  post "/emailconfirmation", to: "pages#email", as: "email_confirmation"

  get "wedding", to: "pages#wedding", as: "wedding"
  get "travel", to: "pages#travel", as: "travel"
  get "about", to: "pages#about", as: "about"
  get "activities", to: "pages#activities", as: "activities"

  get "posts", to: "pages#posts", as: "posts"
  get "posts/:id", to: "pages#show_post", as: "post"
  devise_for :users

  namespace :admin do
    root "base#index"
    resources :users
    get "posts/drafts", to: "posts#drafts", as: "posts_drafts"
    get "posts/dashboard", to: "posts#dashboard", as: "posts_dashboard"
    resources :posts
  end

end

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">

    <div class="row footer-first-row">

      <div class="col-xs-12 text-center">
        <p><small>
          Thank you for being a part of our special day!
        </small></p>
      </div>

    </div>

  </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li><%= link_to "About Us", about_path %></li>
<li><%= link_to "Wedding Details", wedding_path %></li>
<li><%= link_to "Travel Info", travel_path %></li>
<li><%= link_to "Atlanta Activities", activities_path %></li>

<% if !user_signed_in? %>
<li><%#= link_to "Sign in", new_user_session_path %></li>

<% else %>
<li><%= link_to "Protected Page", inside_path %></li>

<% if current_user.admin? %>
<li><%= link_to "Admin", admin_root_path %></li>
<li><%= link_to "Posts", posts_path %></li>

<% end %>

<li><%= link_to "Sign out", destroy_user_session_path, data:{method: :delete} %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en"><head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title><%= @title || "Chelsea and Thomas" %></title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= favicon_link_tag 'apple-touch-icon.png', rel: 'apple-touch-icon', type: 'image/png' %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<!-- NAVBAR
================================================== -->
  <body class="<%= controller.controller_name %> <%= controller.action_name %>">
    <div id="wrap">
      <div class="navbar-wrapper">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </div>

      <!-- header
      ================================================== -->
      <div id="header-content">

      </div><!-- / header -->

      <!-- Marketing messaging and featurettes
      ================================================== -->
      <!-- Wrap the rest of the page in another container to center all the content. -->

      <div class="container marketing">
        <div class="row">
          <div class="col-sm-12">
            <%= yield %>
          </div>
        </div>

      </div><!-- /.container -->
    </div><!-- / wrap -->
    <%= render 'layouts/footer' %>

</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html lang="en"><head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title><%= @title || "Chelsea and Thomas" %></title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= favicon_link_tag 'apple-touch-icon.png', rel: 'apple-touch-icon', type: 'image/png' %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<!-- NAVBAR
================================================== -->
  <body id="home">
    <div id="wrap">
      <div class="navbar-wrapper">
        <div class="container">

          <%= render 'layouts/navigation' %>

        </div>
      </div>


      <!-- Carousel
      ================================================== -->
      <div id="header-content">

        <div class="container">
          <div id="header-text">
            <div class="header-text-inner">
              <h1>Our Story.</h1>
            </div>
            <div class="header-text-inner">
              <p>He asked and she said yes.  Find out how it all came to be.</p>
            </div>
            <div class="header-text-inner">
              <%= link_to "About Us", about_path, :class => "btn btn-lg btn-navy" %>
            </div>
          </div>
        </div>

      </div><!-- /.carousel -->


      <!-- Marketing messaging and featurettes
      ================================================== -->
      <!-- Wrap the rest of the page in another container to center all the content. -->

      <div class="container marketing">
        <div class="row">

          <div class="col-lg-4">

            <%= image_tag("meeting.jpg", :class=>"img-circle feature-image") %>

            <h2>The Big Event</h2>
            <p>
              Eat, drink, and be merry.  <br/>Get ready for a good time!
            </p>
            <p>
              <%= link_to "Wedding Details", wedding_path, :class => "btn btn-navy btn-sm" %>
            </p>
          </div><!-- /.col-lg-4 -->

          <div class="col-lg-4">
            <%= image_tag("engagement.jpg", :class=>"img-circle feature-image") %>

            <h2>Travel Guests</h2>
            <p>All you need to know about getting to the party!</p>
            <p>
              <%= link_to "Travel Info", travel_path, :class => "btn btn-navy btn-sm" %>
            </p>
          </div><!-- /.col-lg-4 -->

          <div class="col-lg-4">
            <%= image_tag("activity.jpg", :class=>"img-circle feature-image") %>

            <h2>Atlanta Activites</h2>
            <p>We can't wait to share our city with you.</p>
            <p>
              <%= link_to "List of Activities", activities_path, :class => "btn btn-navy btn-sm" %>
            </p>
          </div><!-- /.col-lg-4 -->
        </div>

      </div><!-- /.container -->
    </div><!-- / wrap -->

    <%= render 'layouts/footer' %>

</body>
</html>